packages:
  - "cr-sqlite/core"
  - "cr-sqlite/py/correctness"
  - "crsqlite-js"
  - "crsqlite-js/tsbuild-all"
  - "crsqlite-js/packages/browser-tests"
  - "crsqlite-js/packages/client-core"
  - "crsqlite-js/packages/client-server-common"
  - "crsqlite-js/packages/client-websocket"
  - "crsqlite-js/packages/create-web"
  - "crsqlite-js/packages/crsqlite-wasm"
  - "crsqlite-js/packages/node-allinone"
  - "crsqlite-js/packages/node-tests"
  - "crsqlite-js/packages/p2p"
  - "crsqlite-js/packages/react"
  - "crsqlite-js/packages/rx-query"
  - "crsqlite-js/packages/rx-tbl"
  - "crsqlite-js/packages/sandbox"
  - "crsqlite-js/packages/server-core"
  - "crsqlite-js/packages/server-websocket"
  - "crsqlite-js/packages/xplat-api"
  - "crsqlite-js/packages/xplat-tests"
  - "crsqlite-js/deps/wa-sqlite"
  - "strut/app"
  - "strut/app-server-shared"
  - "strut/server"
  - "strut/deps/access-token-jwt"
  - "strut/deps/oauth2-bearer"
  - "model-js/ts/build-all"
  - "model-js/ts/packages/cache"
  - "model-js/ts/packages/codegen-api"
  - "model-js/ts/packages/codegen-cli"
  - "model-js/ts/packages/codegen-sql"
  - "model-js/ts/packages/codegen-ts"
  - "model-js/ts/packages/config"
  - "model-js/ts/packages/feature-gates"
  - "model-js/ts/packages/grammar-extension-api"
  - "model-js/ts/packages/id"
  - "model-js/ts/packages/instrument"
  - "model-js/ts/packages/migration"
  - "model-js/ts/packages/model"
  - "model-js/ts/packages/model-persisted"
  - "model-js/ts/packages/query"
  - "model-js/ts/packages/react"
  - "model-js/ts/packages/runtime"
  - "model-js/ts/packages/schema"
  - "model-js/ts/packages/schema-api"
  - "model-js/ts/packages/sql"
  - "model-js/ts/packages/util"
  - "model-js/ts/packages/value"
  - "model-js/ts/packages/zone"
  - "model-js/ts/connectors/sqlite3-connector"
  - "model-js/ts/connectors/wa-sqlite-connector"
  - "model-js/ts/integration-tests/data-model"
  - "misc-js/typescript/packages/counter"
  - "misc-js/typescript/packages/counter.ui.launcher"
  - "misc-js/typescript/packages/events"
  - "misc-js/typescript/packages/sid"
  - "misc-js/typescript/packages/utils"
  - "misc-js/typescript/build-all"
  - "template-web/frameworks/react/app"
  - "template-web/shared"
  - "template-web/sync-server"
  - "live-examples-js"
